excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jaredliang.github.io
title: Jared's Notebook
email: jeweiliang@gmail.com
author: jaredliang
description: Jared's blog about trading 
paginate: 3
google_analytics: 